language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
env:
  global:
    - MINICONDA_BUILD_FOLDER=condatmp
matrix:
  include:
    - os: Linux
      python: 3.5
before_install:
  - .travis/before_install.sh
install:
  - .travis/install.sh
before_script:
  - .travis/before_script.sh
script:
  - .travis/script.sh
after_success:
  - .travis/after_success.sh
after_script:
  - .travis/after_script.sh
