package:
  name: "redis_importer"
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
source:
  path: ../
requirements:
  build:
    - python
    - setuptools
    - redis-py
    - t2db_objects >=0.7.6
  run:
    - python
    - redis-py
    - t2db_objects >=0.7.6
test:
  imports:
    - redis_importer.importer
about:
  home: https://github.com/brian/redis_importer
  license: GPLv3
